### ISSUE TITLE
Add a `:separator` option to concat command

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#111]
I think it would make sense for the `concat` command to have a `:separator` keyword that would add a string in between the concatenated strings.

```elisp
(loopy (list word '("I" "am" "sam"))
       (concating word :separator "\s"))

;; => "I am sam"
```

**Comment by okamsn** [comment]
This would be nice to have, but avoiding a trailing separator would be difficult, since the command doesn't know when the last iteration will be.

Some sort of finalizing update (similar to reversing lists or the `:result-type` keyword argument) wouldn't quite work either. Since the variable can be modified by more than one command, data at the end might not be the separator.

**Comment by okamsn** [comment]
For the record, something like

``` emacs-lisp
(loopy (list word '("I" "am" "sam"))
       (concating word)
       (concating "\s")
       (finally-return (substring loopy-result 0 -1)))
```

isn't really inefficient, since the function `concat` is only called once.  The
current optimized implementation works like `mapconcat`, which creates a list of
sequences and passes them all to `concat` at once.  You can see from the below
expansions that, ignoring a few small nits, there isn't really much room for
improvement.

``` emacs-lisp
;; `loopy' expansion
(let* ((loopy-result nil))
  (let* ((list-838 '("I" "am" "sam"))
         (word nil))
    (let ((loopy-first-iteration t))
      (progn
        (while (consp list-838)
          (setq word (car list-838))
          (setq loopy-result (cons word loopy-result))
          (setq loopy-result (cons " " loopy-result))
          (setq list-838 (cdr list-838))
          (setq loopy-first-iteration nil))
        (setq loopy-result (apply #'concat (nreverse loopy-result)))
        loopy-result)
      (substring loopy-result 0 -1))))
```

``` emacs-lisp
;; `dolist' version
(let ((result nil))
  (dolist (word '("I" "am" "sam"))
    (push word result)
    (push "\s" result))
  (substring (apply #'concat (nreverse result)) 0 -1))

;; `dolist' expansion
(let ((result nil))
  (let ((--dolist-tail-- '("I" "am" "sam"))
        word)
    (while --dolist-tail--
      (setq word (car --dolist-tail--))
      (setq result (cons word result))
      (setq result (cons " " result))
      (setq --dolist-tail-- (cdr --dolist-tail--))))
  (substring (apply #'concat (nreverse result)) 0 -1))
```

**Comment by Luis-Henriquez-Perez** [comment]
> the data at the end might not be the separator

That's a good point. Maybe then it doesn't make sense to have a separator. I'll illustrate your point here for clarity:

```
;; Doesn't know when last iteration is.
(loopy (list word '("I" "am" "sam"))
       (concating word :separator "\s")
       (concating "*"))

;; Would want?
"I *am *sam*"

;; But may end up with the following if we try to blindly remove the last separator.
"I *am *sam"
```

**Comment by Luis-Henriquez-Perez** [comment]
I am ok to close this. This would have been nice, but I think it can't happen for the reasons we discussed.
