### ISSUE TITLE
idea: `loop` itelf should be a loop command

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [okamsn/loopy#31]
I've had a craving for using the `loop` command within the `loop` command. It seems intuitive to me. Also, I don't like having to declare the whole loopy macro all over again when I'm already in the macro. And it shortens the syntax for nested loops significantly. 

```elisp
(loopy (loop (list store petstores)
	       (append (loop (list dog dogs)
			     ...
			     (collect dog)))
	       (loop (list cat cats)
		     ...
		     (do (some-side-effect)))))
		     (do (message "meow")))))
```

**Comment by okamsn** [comment]
I have been thinking about adding `loop` as a loop command. Please see #33 for more on this.

> ``` elisp
> (append (loop (list dog dogs)
> ```

Even in #33, I would like to keep things so that the above usage would require another use of the`loopy` macro instead of a `loop` loop command.

The arguments of loop commands are currently not evaluated until after the macro expands, and it is easier to not try to recurse through them like CL's `iterate` package. Instead, I would like to make using the `loopy` macro simpler so that calling a `loopy` macro inside another does not take as much typing. I think that the changes proposed in #33 will improve the situation.

**Comment by okamsn** [comment]
Update: #33  has been implemented.

Sub-loops can now be created using the `sub-loop` (with alias `loop`) command.
Sub-loops do not have a return value of their own, instead accumulating into the
same `loopy-result` as the super-loop.  A sub-loop can access any variable that
exists in the super-loop, but variables used in sub-loops (such as `cat` or
`dog` in the example) are only accessible in the sub-loop itself.
