### ISSUE TITLE
Create a `group` command for use in `if`

### ISSUE THREAD

**Issue by okamsn** [okamsn/loopy#5]
There's currently no equivalent of a `progn` command for loop commands, but it
might be useful to have one.  For example, as the first sub-command in the `if`
command.

Here's a quick example:

``` emacs-lisp
(loopy ((list i '(2 4 5))
        (if (cl-oddp i)
            (group
               (expr failure t)
               (do (message "Warning: odd found")))
          (expr failure nil))
        (count failures failure))
       (return failures)) ; => 1
```

`progn` is currently an alias for the `do` command.  Should that be changed to
this?

**Comment by Luis-Henriquez-Perez** [comment]
Perhaps, I'm misunderstanding something. I'm confused why this doesn't work. I assumed that `loopy` clauses could be arbitrarily nested in a loopy form.


```elisp
;; I thought you could arbitrarily nest loopy clauses within lisp forms. But
;; instead, you get an error.

;; Debugger entered--Lisp error: (void-function collect)
;; (collect failure t)
(loopy ((list i '(2 4 5))
        (if (cl-oddp i)
	    (progn (collect failure t))
          (collect failure nil))
        (count failures failure))
       (return failures))

;; What this implies is that...

;; This works.
(loopy ((list i '(2 4 5))
        (if (cl-oddp i)
	    (expr failure t)
          (expr failure nil))
        (count failures failure))
       (return failures)) ; => 1

;; But this doesn't.
(loopy ((list i '(2 4 5))
        (if (cl-oddp i)
            ;; Only difference is I added a progn, which in theory shouldn't change anything.
	    (progn (expr failure t))
          (expr failure nil))
        (count failures failure))
       (return failures))
```
Is this is what you meant when you said:

> While =iterate= can apparently embed its looping constructs in
  arbitrary code, I don’t think that either =loopy= or =for= allow that.

Instead of adding a `group` clause or making `do` do this, would it be possible add this arbitrary nesting as a feature?

**Comment by okamsn** [comment]
> Is this is what you meant when you said:
>
> > While =iterate= can apparently embed its looping constructs in arbitrary code,
>   I don’t think that either =loopy= or =for= allow that.
>
> Instead of adding a `group` clause or making `do` do this, would it be possible
> add this arbitrary nesting as a feature?


Yes, `loopy` only allows normal Lisp expressions in specific locations.  I think
that Common Lisp's [`for` library](https://github.com/Shinmera/for/) works the
same way.

This approach is much simpler than what the
[`iterate`](https://gitlab.common-lisp.net/iterate/iterate/-/blob/master/iterate.lisp)
library does.  Loopy's approach is to just create lists of expressions to
substitute into the expanded code that is returned by the macro.

While I'm not against having arbitrarily nested code, I suspect that adding it
would take more than my current skill-level in Lisp. I'm also assuming that
featureful loop commands can be "good enough" when compared to the usefulness
added by arbitrary nesting.

For example, I assume that using subcommands in a `when` command is (at least
nearly) as useful as using `iter`'s clauses in a normal `when` form.  I also
assume that this approach allows for easy extensibility, so that users can add
their own features, if needed.

That being said, if there are situations where you feel that the current
command-based approach is insufficient, please let me know.  I can only judge
things by my own experiences, and I am not very familiar with `iter` or other
similar packages.

**Comment by Luis-Henriquez-Perez** [comment]
> For example, I assume that using subcommands in a when command is (at least
nearly) as useful as using iter's clauses in a normal when form.

Yes. It certainly is easy to forget that `loopy` has this limitation in many
cases because the clauses are well chosen. Although I do lament the prospect of
having to consider the level I'm at before using a loopy clause.

> if there are situations where you feel that the current
command-based approach is insufficient, please let me know. I can only judge
things by my own experiences, and I am not very familiar with iter or other
similar packages.

My general feeling that if I already pass in my lisp form to "loopy",
it should manage the arbitrarily nested clauses for me.
That being said, I haven't used loopy or iter extensively. This is just an
_impression_ of what I _predict_ I won't like. So it's just pure speculation and
I don't want you to go down a potentially much more difficult route just for
that. I think it's best just to sit on this idea for now and as we and others
use `loopy` more and we have a better understanding of the consequences of this
implementation maybe we can decide to add this feature (gradually) in the future
(or possibly decide that it's not worth it).

> While I'm not against having arbitrarily nested code, I suspect that adding it
would take more than my current skill-level in Lisp.

Yea, more than my current level either. I'll take a stab at it in my own
branch during my free time. Who knows? maybe I'll end up with a nice PR.

**Comment by okamsn** [comment]
A `group` command was added. `progn` was removed as alias of `do`. There is now no command with an alias `progn`, as that might cause confusion with `group` and `do`.

`do` is a decent command name, as it is the same word that `cl-loop` uses. `group` is probably a less decent name, but makes some sense as it groups some expressions under a `progn`.
